apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: Flask-Portfolio
spec:
  replicas: 3  # Number of instances you want to run
  selector:
    matchLabels:
      app: Flask-Portfolio
  template:
    metadata:
      labels:
        app: Flask-Portfolio
    spec:
      containers:
        - name: Flask-Portfolio
          image: akscr01sample.azurecr.io/Flask-Portfolio:latest  # Specify your image from ACR
          ports:
            - containerPort: 5000  # Flask app runs on port 5000 inside the container
          imagePullPolicy: Always  # Always pull the latest image from ACR
      imagePullSecrets:
        - name: acr-auth  # Secret for accessing ACR (will create it in the next step)
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  selector:
    app: Flask-Portfolio
  ports:
    - protocol: TCP
      port: 80  # The external port
      targetPort: 5000  # Internal port that Flask listens on
  type: LoadBalancer  # Expose the service via LoadBalancer for external access
